#- name: install dependence packages
#  yum: name={{ item }} state=installed
#  with_items:
#    - gcc
#    - zlib-devel 
#    - pcre-devel
#    - openssl-devel

- name: wget redis ver.{{ redis_version }} package
  get_url: url={{ redis_src_url }} dest=/var/tmp

- name: expand redis 
  shell: tar xzvf redis-{{ redis_version }}.tar.gz chdir=/var/tmp

- name: install redis
  shell: >-
    make &&
    make PREFIX={{ redis_prefix }} install chdir=/var/tmp/redis-{{ redis_version }} 
