- name: add user
  user: name={{ redis_user }} home={{ redis_home_dir }}

- name: init dir 
  file: dest={{ item }} state=directory owner={{ redis_user }}
  with_items: [redis_log_dir, redis_dir, redis_conf_dir]

- name: create startup script
  template: src=etc/init/redis.conf.j2 dest=/etc/init/redis.conf owner=root group=root mode=0755

- name: configure server conf 
  template: src=etc/redis/redis.conf.j2 dest={{ redis_server_conf_path }} mode=0755
